const DELETE_USER="user:DELETE_USER"
const GET_ALL_USERS="user:GET_ALL_USERS"
const DELETE_PRODUCT="products:DELETE_PRODUCT"
const GET_ALL_PRODUCTS="products:GET_ALL_PRODUCTS"
const DELETE_VENDOR="vendor:DELETE_VENDOR"
const GET_ALL_VENDORS="vendor:GET_ALL_VENDORS"
const DELETE_DELIVERY="delivery:DELETE_DELIVERY"
const GET_ALL_DELIVERIES="delivery:GET_ALL_DELIVERIES"
const DELETE_ITEM="item:DELETE_ITEM"
const GET_ALL_ITEMS="item:GET_ALL_ITEMS"
const DELETE_ORDER="orders:DELETE_ORDER"
const GET_ALL_ORDERS="orders:GET_ALL_ORDERS"
const DELETE_REVIEW="review:DELETE_REVIEW"
const GET_ALL_REVIEWS="review:GET_ALL_REVIEWS"
const DELETE_WISHLIST="wishlist:DELETE_WISHLIST"
const GET_ALL_WISHLISTS="wishlist:GET_ALL_WISHLISTS"


module.exports={
    GET_ALL_PRODUCTS,
    GET_ALL_USERS,
    GET_ALL_VENDORS,
    GET_ALL_DELIVERIES,
    GET_ALL_ITEMS,
    GET_ALL_ORDERS,
    GET_ALL_REVIEWS,
    GET_ALL_WISHLISTS,
    DELETE_VENDOR,
    DELETE_PRODUCT,
    DELETE_USER,
    DELETE_DELIVERY,
    DELETE_ITEM,
    DELETE_ORDER,
    DELETE_REVIEW,
    DELETE_WISHLIST
}